Fix HAVE_GMTIME and HAVE_GMTIME_R declarations
Fix for systems, that do not have `gm_time` or `gm_time_r` funtions.

Bug found under MinGW 32-bit for Windows, it doesn't have `gmtime_r` and
compilation breaks with:

```common.c.obj: undefined reference to 'gmtime_r'```